### ISSUE TITLE
Could you please public the trained model

### ISSUE THREAD

**Issue by Fino2020** [aashishyadavally/nd-slicer#1]
I'm very sorry to bother you, I'm very interested in your work and would like to use your framework directly without training, could you please provide the trained model？

**Comment by Fino2020** [comment]
Another question is that there is no `full-dataset.jsonl` file in the dataset when executing the `process.py`
here is the error message:
![image](https://github.com/aashishyadavally/nd-slicer/assets/66312471/9f646e02-5687-4453-bcfd-e404feb54a4d)
and here is the architecture of the download dataset:
![image](https://github.com/aashishyadavally/nd-slicer/assets/66312471/c3248dee-c20d-4096-b994-b4d8ad218fd5)

**Comment by aashishyadavally** [comment]
Hi @Fino2020! Thank you so much for your interest in our work..
With regards to the artifact, I am working on updating the entire repository with more instructions and all relevant models (mainly towards submitting it to the FSE 2024 A/E track). Please check the repository again in a week or two :)

The error above, is already handled by building the datasets by following all the processing steps used in the paper, and this is a check to make sure all of ``full-dataset.jsonl``, ``train-dataset.jsonl``, ``val-dataset.jsonl``, ``test-dataset.jsonl`` are not created repeatedly. I will add more instructions in this regard as well :)

**Comment by aashishyadavally** [comment]
@Fino2020: I have updated the repository with detailed instructions to process/directly use the data, links to model weights, and run instructions. Let me know if this helps!
